# Generated by Django 3.1.6 on 2021-02-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_blog', '0003_auto_20210211_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='uncategorized', max_length=255),
        ),
    ]
