# Generated by Django 3.1.6 on 2021-03-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_blog', '0007_post_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='headr_images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='uncatpegorized', max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='', max_length=255),
        ),
    ]
