# Generated by Django 3.1.6 on 2021-03-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_blog', '0010_auto_20210302_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='linkedin_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
